### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by webbrowser11** [G1aD05/scratchcon#1]
have you hosted the public version of the package on PyPI?

**Comment by G1aD05** [comment]
Here's the install command `pip install scratchcon` I couldn't find anything in settings that could make it public.

**Comment by webbrowser11** [comment]
but is it on the python package index (aka [PyPI](https://pypi.org/))?

**Comment by webbrowser11** [comment]
like just GIVE me the link it works for anyone and is public by defualt

**Comment by webbrowser11** [comment]
also you cant upload a package to python without an account on the python package index, so therefore `pip install scratchcon` wont work unless it is a package uploaded PUBLICLY (which is defualt) to the python package index ([PyPI](https://pypi.org/)).

**Comment by webbrowser11** [comment]
err wait i found it https://pypi.org/project/scratchcon/

**Comment by G1aD05** [comment]
Sorry for not replying I was busy

**Comment by webbrowser11** [comment]
k
